# Generated by Django 4.2.11 on 2026-03-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='overtime_allowance',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('modified', 'Modified after verification')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='admin_id',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='admin_id',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pfdetail',
            name='esic_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salary',
            name='admin_id',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='extra_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='gst_portion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='ot_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='snapshot_esic_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salary',
            name='snapshot_pf_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salary',
            name='snapshot_uan_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pfdetail',
            name='pf_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pfdetail',
            name='uan_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salary',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
