# Generated by Django 4.2.11 on 2026-03-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_remove_bankdetail_is_verified_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ot_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salary Updates',
                'ordering': ['-month'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='pfdetail',
            name='employee_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pfdetail',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pfdetail',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pfdetail',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_details_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pfdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Details'), ('added', 'Details Added')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.AddField(
            model_name='salaryupdate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryupdate',
            unique_together={('employee', 'month')},
        ),
    ]
