# Generated by Django 4.2.11 on 2026-04-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_salaryupdate_alter_salary_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Wage')], default='monthly', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('admin_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.jobrole'),
        ),
    ]
