# Generated by Django 4.2.11 on 2026-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_is_custom_override',
            field=models.BooleanField(default=False),
        ),
    ]
