# Generated by Django 4.2.11 on 2026-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_admin_id_category_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('upi', 'UPI/Online')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
