# Generated by Django 4.2.11 on 2026-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
