# Generated by Django 4.2.11 on 2026-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_admin_id_user_parent_admin_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_id',
            field=models.CharField(blank=True, db_index=True, default='PENDING', max_length=20, null=True),
        ),
    ]
