# Generated by Django 4.2.11 on 2026-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='admin_id',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
    ]
