# Generated by Django 4.2.11 on 2026-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_income_type_income_location_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
