# Generated by Django 4.2.11 on 2026-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_admin_id'),
        ('income', '0003_alter_income_title'),
    ]

    operations = [
    ]
